### ISSUE TITLE
Issue on page /Slurry_Adsorption.html

### ISSUE THREAD

**Issue by nikigusev** [msalvalaglio/PSSP_notebook#1]
I think I noticed a mistake in the derivation, it says that:

> " 'a' represents the particles mass per unit of fluid volume.", and it is said to be: 'a = P/V' 

but making a dimensional analysis on the flux equation and the mass balance 
gives inconsistent results. I also attach a screenshot of what I mean so it is more clear:

<img width="1440" alt="Снимок экрана 2021-02-10 в 01 58 21" src="https://user-images.githubusercontent.com/78820910/107427908-b5ae1e00-6b43-11eb-97b6-46dc7521bc43.png">

From literature and dimensional analysis I think that: 

> 'a' is and should be the external surface area of adsorbent per unit volume of liquid, and it would be: 'a = (P/V) * As' where As is the particle surface area in m2/kg of particles.

Also in the problem statement the particle surface area is not given to us, so I assume that this problem has no unique solution.

**Comment by msalvalaglio** [comment]
Hi Nikita, thanks for pointing this out - this derivation went though a couple of iterations and adaptations and I think I know what might have happened there. In an earlier version I was giving the average size of the particles, and defining a as the specific area. In a later version, for consistency with continuous versions of this problem I have switched to defining Sp as the mass of adsorbent. This is what is typically done in practical applications, and provides a much more reasonable way of translating this problem from batch to continuous configurations. I will revise it to make the notation and units fully consistent.

**Comment by msalvalaglio** [comment]
Fixed the issue by explicitly introducing the surface area of particles in the Batch section, and rewriting the continuous section to introduce the mass flow rate of adsorbent. Also, added exercise on continuous slurry adsorption.
