### ISSUE TITLE
Issue on page /Exercise_W9_2021.html

### ISSUE THREAD

**Issue by AhmadEblagh205** [msalvalaglio/PSSP_notebook#2]
In the excel dataset, the headings are labelled as MA(L) and MB(L) respectively. I believe this is a mistake as the problem statement affirms that the data is for cumulative particle size distribution NA(L) and NB(L).

**Comment by AhmadEblagh205** [comment]
Additionally, there seems to be a mistake in the data for length in the excel spreadsheet. From a length of 9.9 onwards, the length goes back to 0.2, but I believe this is supposed to be 10.2 given the data in the plain text file

**Comment by msalvalaglio** [comment]
Hi Ahmad, noted and fixed it! Thanks for spotting the problem with the xls.
