### ISSUE TITLE
Issue on page /MSMPR_crystallizer.html

### ISSUE THREAD

**Issue by AhmadEblagh205** [msalvalaglio/PSSP_notebook#4]
I also noticed a few spelling mistakes, I know it's trivial but it's good to get it fixed. The first typo occurs above equation 110, where mass is spelt as 'nass'. The next typo I noticed occurs below equation 117 where physical is spelt 'pyisical'.

**Comment by msalvalaglio** [comment]
Hi Ahmad - absolutely. 

I have corrected it as 
-nass-> mass
-phisical -> physical 

thanks for spotting this!
