### ISSUE TITLE
Issue on page /Exercise_W10_2021.html

### ISSUE THREAD

**Issue by nikigusev** [msalvalaglio/PSSP_notebook#5]
In the code where you compute mA and t_2 you forgot the denominator of the constant rate drying term, the equations should be such,

`mA = (1/t_1) * ((w0_1-w_c)/(w_c-w_e) + np.log((w_c-w_e)/(w_1-w_e)))`
`t_2 = (1/mA) * ((w0_2-w_c)/(w_c-w_e) + np.log((w_c-w_e)/(w_2-w_e)))`

Notice that the denominator (w_c-w_e)  is missing in the solution code, but is present when deriving the equations above it.

The same is for the next task, when plotting the graph, the denominator is also missing in the equation in the solution code there.

**Comment by mme-ucl** [comment]
Thanks for pointing this out, the solution has now been fixed.
